"""Surrogate Phase2 G_bar estimator — Phase1 6D/3D space, VLA-free.

Implements ``budget_aware_phase1_boundary_rule.md`` §3 as a per-buffer
signal computable during Phase1 without VLA encoder, curobo, or gRPC.

Surrogate definitions (spec §3 + §15.1 allow "임시 key during Phase1"):

    state_key  (6D)  = terminal_region_key  = [x_EE, x_EE − goal]   (existing)
    action key (3D)  = subgoal xyz          ("where the action goes")

For each probe ξ generated by perturbing existing subgoal anchors:

    ΔH_A(ξ, D)     = log(1 + mean k-NN distance from probe subgoal to db subgoals)
                     — action-novelty proxy
    ΔH_A|S(ξ, D)   = variance increase of subgoals among state-space neighbors
                     within ρ_m of the probe state                   (covered-only)
    M_MI(ξ, D)     = β · ΔH_A − λ · ΔH_A|S
    M̃_MI          = (M_MI − μ_M) / (σ_M + ε)        batch-normalized
    G_bar_phase2  = E_ξ[max(M̃_MI, 0)]                spec §3 definition

Result is *signal-quality* not VLA-quantitatively-equal: cross-run
G_bar values are comparable to themselves, not to a true Phase2 run.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass
class GainEstimatorConfig:
    n_probes_per_skill: int = 8       # probes per skill
    sigma: float = 0.05               # probe perturbation σ (m)
    clip_factor: float = 2.0          # clip = clip_factor × σ
    k_nn: int = 3                     # kNN for ΔH_A
    radius_k: int = 5                 # kNN k for ρ_m
    radius_quantile: float = 0.7      # ρ_m quantile
    beta: float = 1.0                 # M_MI weight on ΔH_A
    lambda_: float = 1.0              # M_MI weight on ΔH_A|S
    eps: float = 1e-6
    rng_seed: int = 0


def _state_descriptor(ee: np.ndarray, goal: np.ndarray) -> np.ndarray:
    """[x_EE, x_EE − goal] — same builder as terminal_descriptor."""
    ee = np.asarray(ee, dtype=np.float64).reshape(3)
    g = np.asarray(goal, dtype=np.float64).reshape(3)
    return np.concatenate([ee, ee - g])


def _sample_perturbed(anchor: np.ndarray, sigma: float, clip: float,
                      rng: np.random.Generator) -> np.ndarray:
    """Truncated Gaussian around anchor (3D)."""
    for _ in range(50):
        d = rng.normal(0.0, sigma, 3)
        if float(np.linalg.norm(d)) <= clip:
            return anchor + d
    n = float(np.linalg.norm(d))
    return anchor + (d / n * clip if n > 0 else d)


def _knn_mean_dist(query: np.ndarray, refs: np.ndarray, k: int) -> float:
    """Mean of top-k smallest distances from query to refs."""
    if len(refs) == 0:
        return 0.0
    d = np.linalg.norm(refs - query[None, :], axis=1)
    k = min(k, len(refs))
    return float(np.partition(d, k - 1)[:k].mean())


def _state_radius(state_keys: np.ndarray, k: int, q: float) -> float:
    """ρ_m = quantile_q of intra-buffer k-NN distance."""
    n = len(state_keys)
    if n < 2:
        return 0.0
    k = min(k, n - 1)
    means = []
    for i in range(n):
        d = np.linalg.norm(state_keys - state_keys[i:i + 1], axis=1)
        d = np.sort(d)[1:k + 1]  # exclude self
        if len(d):
            means.append(d.mean())
    return float(np.quantile(means, q)) if means else 0.0


def estimate_phase2_gain(buffer, cfg: GainEstimatorConfig | None = None
                         ) -> tuple[float, dict]:
    """Compute surrogate G_bar_phase2 from a Phase1 SubgoalBuffer.

    Returns ``(g_bar, meta)`` where ``meta`` carries diagnostics
    (n_probes, per_skill counts, raw stats) for logging.

    Cold-start (per-skill buffer < k_nn+1 or radius=0) skips that skill.
    Returns ``(0.0, {...})`` if no probes scored.
    """
    cfg = cfg or GainEstimatorConfig()
    rng = np.random.default_rng(cfg.rng_seed)

    m_mi_all: list[float] = []
    per_skill: dict[str, int] = {}

    for skill_id in buffer.skill_ids():
        entries = buffer.entries(skill_id)
        if len(entries) < max(cfg.k_nn + 1, 2):
            continue

        db_sg = np.stack([
            np.asarray(e.subgoal, dtype=np.float64).reshape(3) for e in entries
        ])
        db_sk = np.stack([
            np.asarray(e.terminal_region_key, dtype=np.float64) for e in entries
        ])
        radius = _state_radius(db_sk, cfg.radius_k, cfg.radius_quantile)
        if radius <= 0:
            continue

        n_this = 0
        for _ in range(cfg.n_probes_per_skill):
            idx = int(rng.integers(0, len(entries)))
            anchor_sg = db_sg[idx]
            anchor_ee = db_sk[idx][:3]    # recover x_EE from [ee, ee − goal]

            probe_sg = _sample_perturbed(
                anchor_sg, cfg.sigma, cfg.clip_factor * cfg.sigma, rng)
            probe_sk = _state_descriptor(anchor_ee, probe_sg)

            # ΔH_A — action-space novelty
            delta_a = float(np.log1p(_knn_mean_dist(probe_sg, db_sg, cfg.k_nn)))

            # ΔH_A|S — covered-region action variance INCREASE
            sd = np.linalg.norm(db_sk - probe_sk[None, :], axis=1)
            covered = db_sg[sd < radius]
            if len(covered) < 2:
                delta_amb = 0.0
            else:
                std_before = covered.std(axis=0)
                std_after = np.vstack([covered, probe_sg[None, :]]).std(axis=0)
                delta_amb = float(np.linalg.norm(std_after - std_before))

            m_mi_all.append(cfg.beta * delta_a - cfg.lambda_ * delta_amb)
            n_this += 1
        if n_this:
            per_skill[str(skill_id)] = n_this

    if not m_mi_all:
        return 0.0, {"n_probes": 0, "per_skill": {}, "raw_mean": 0.0, "raw_std": 0.0}

    arr = np.asarray(m_mi_all, dtype=np.float64)
    mu, sd = float(arr.mean()), float(arr.std())
    m_norm = (arr - mu) / (sd + cfg.eps)
    g_bar = float(np.maximum(m_norm, 0.0).mean())
    return g_bar, {
        "n_probes": len(arr),
        "per_skill": per_skill,
        "raw_mean": mu,
        "raw_std": sd,
    }
