"""Per-episode Phase1 readiness check + auto-stop hook (Stage 1 wire-in).

Drives the live ``run_multiple_episodes`` / ``resume_multiple_episodes`` loop
with Phase1 termination semantics from method3 §15:

  Phase1 transition / stop:
      (t ≥ B₁_min ∧ R_ready > τ_ready)  ∨  (t ≥ B₁_max)

Since hardware Phase2 (encoder training + candidate generation + execution) is
not yet wired, "transition" here means **early stop with `transition` reason**
— the run terminates and the user can move on. When Stage 2/3 land, this hook
can be replaced by full `Method3Acquisition` driving the loop.

Readiness measurement (R_ready)
-------------------------------
The spec wants probes generated by the Phase2 candidate generator, which we
don't have yet. As a hardware-free proxy this hook uses **leave-one-out
self-coverage** over the live ``SubgoalBuffer``: each skill's entries treat
their ``terminal_region_key`` as a single-window probe and compare against the
remaining entries as the db. Same params (radius_k, radius_quantile, k_min,
state_ready_threshold) as the spec method, so threshold tuning intuition
carries over.

Interpretation:
  R_ready high  ⇔ buffer is self-dense in state-key space → support is broad
                  enough that any new episode will land in covered region.
  R_ready low   ⇔ buffer is sparse → keep collecting.

Opt-in via ``recording_config_ws*.yaml``::

    method3_phase1:
      enabled: true               # default false — full opt-in
      phase1_min: 20              # B₁_min
      phase1_max: 50              # B₁_max  (cap regardless of readiness)
      state_ready_threshold: 0.7   # R_ready threshold
      k_min: 3
      radius_k: 5
      radius_quantile: 0.7
      auto_stop_on_ready: true    # false → measure & log only, do not stop
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from method3.phase_control.phase1_readiness import (
    Phase1ReadinessConfig,
    Phase1ReadinessReport,
    SkillProbe,
    evaluate_phase1_readiness,
)


@dataclass
class Phase1ReadinessHookConfig:
    """Live-pipeline-side wrapper for ``Phase1ReadinessConfig`` + loop policy.

    Two threshold knobs (renamed from spec's terse τ-prefixed names for
    readability in user-facing yaml/logs):

    * ``state_ready_threshold`` — minimum ``R_ready`` (state-support coverage)
      to consider Phase1 done. spec τ_ready, default 0.7.
    * ``phase2_potential_gain_threshold`` — minimum ``G_bar_phase2`` (expected
      per-episode positive MI gain if we transitioned now). spec τ_gain.
      0 (default) disables gain gating ⇒ R_ready alone decides.
    """

    enabled: bool = False
    phase1_min: int = 20
    phase1_max: int = 50
    state_ready_threshold: float = 0.7
    k_min: int = 3
    radius_k: int = 5
    radius_quantile: float = 0.7
    auto_stop_on_ready: bool = True
    # G_bar_phase2 gating (budget_aware_phase1_boundary_rule.md §3,§5).
    # threshold == 0 → gating disabled (Stage 1 behaviour: state-readiness only).
    phase2_potential_gain_threshold: float = 0.0
    n_probes_per_skill: int = 8
    gain_beta: float = 1.0
    gain_lambda: float = 1.0
    # Execution scheduling — round_robin is the default (and only documented
    # mode). seed_major remains as an opt-in legacy escape hatch via yaml.
    #   round_robin: seed0·1, seed1·1, ..., seedN·1, seed0·2, ..., seedN·K.
    #                Every seed gets +1 each round; hook checked end-of-round
    #                so early stop preserves balanced coverage AND R_ready
    #                stays measurement-validity (measured on balanced buffer).
    #                Per-seed minimum coverage is enforced *implicitly* by
    #                ``phase1_min`` — first end-of-round with ep >= phase1_min
    #                automatically has every seed at ``ceil(phase1_min/N)``.
    #   seed_major  (legacy): seed0 ×K, then seed1 ×K, ..., then seedN ×K.
    #                Early stop here means later seeds get 0 episodes →
    #                biased seed coverage + biased R_ready signal.
    schedule_mode: str = "round_robin"

    def to_readiness_config(self) -> Phase1ReadinessConfig:
        return Phase1ReadinessConfig(
            tau_ready=self.state_ready_threshold,   # spec name on the lib side
            k_min=self.k_min,
            radius_k=self.radius_k,
            radius_quantile=self.radius_quantile,
        )

    @classmethod
    def from_yaml_section(cls, section: Optional[dict]) -> "Phase1ReadinessHookConfig":
        """Build from the ``readiness:`` block. Accepts both new names and the
        legacy ``tau_ready`` / ``tau_gain`` names (with a deprecation warning).
        Unknown keys ignored.
        """
        if not section:
            return cls()
        d = dict(section)

        # Back-compat: tau_ready → state_ready_threshold, tau_gain → phase2_potential_gain_threshold.
        legacy = []
        if "tau_ready" in d and "state_ready_threshold" not in d:
            d["state_ready_threshold"] = d["tau_ready"]
            legacy.append("tau_ready → state_ready_threshold")
        if "tau_gain" in d and "phase2_potential_gain_threshold" not in d:
            d["phase2_potential_gain_threshold"] = d["tau_gain"]
            legacy.append("tau_gain → phase2_potential_gain_threshold")
        if legacy:
            print(f"[method3:phase1] deprecation — please rename: {', '.join(legacy)}")

        return cls(
            enabled=bool(d.get("enabled", False)),
            phase1_min=int(d.get("phase1_min", 20)),
            phase1_max=int(d.get("phase1_max", 50)),
            state_ready_threshold=float(d.get("state_ready_threshold", 0.7)),
            k_min=int(d.get("k_min", 3)),
            radius_k=int(d.get("radius_k", 5)),
            radius_quantile=float(d.get("radius_quantile", 0.7)),
            auto_stop_on_ready=bool(d.get("auto_stop_on_ready", True)),
            phase2_potential_gain_threshold=float(
                d.get("phase2_potential_gain_threshold", 0.0)),
            n_probes_per_skill=int(d.get("n_probes_per_skill", 8)),
            gain_beta=float(d.get("gain_beta", 1.0)),
            gain_lambda=float(d.get("gain_lambda", 1.0)),
            schedule_mode=str(d.get("schedule_mode", "round_robin")),
        )


def measure_phase1_readiness_loo(
    buffer, config: Phase1ReadinessConfig,
) -> Phase1ReadinessReport:
    """Leave-one-out self-coverage proxy for Phase1 readiness from live buffer.

    Each ``SubgoalBufferEntry.terminal_region_key`` becomes a 1-window probe.
    The db for that skill is the full set of keys (LOO is approximated — the
    entry's own key matches itself with distance 0 and is necessarily one
    neighbor; with ``k_min=3`` we need ≥2 *other* neighbors within ρ_m, so
    self-match doesn't trivially saturate the metric).

    Returns ``Phase1ReadinessReport`` matching the spec calculator's interface
    so logging/threshold logic stays identical.
    """
    probes: list[SkillProbe] = []
    for skill_id in buffer.skill_ids():
        entries = buffer.entries(skill_id)
        if len(entries) < 2:
            # Cold start — evaluate_phase1_readiness already returns 0.0 for
            # under-populated skills; pass a placeholder so the skill appears
            # in the report dict.
            probes.append(SkillProbe(
                skill_id=str(skill_id),
                probe_candidate_keys=[],
                db_state_keys=np.empty((0, 1), dtype=np.float64),
            ))
            continue
        keys = np.stack([
            np.asarray(e.terminal_region_key, dtype=np.float64) for e in entries
        ])
        probe_candidates = [k.reshape(1, -1) for k in keys]   # each entry = 1-window probe
        probes.append(SkillProbe(
            skill_id=str(skill_id),
            probe_candidate_keys=probe_candidates,
            db_state_keys=keys,
        ))
    return evaluate_phase1_readiness(probes, config)


@dataclass
class Phase1ReadinessHook:
    def set_readiness_trace(self, path) -> None:
        """jsonl 경로 설정 — 매 check() 마다 readiness_report append."""
        self._readiness_trace_path = str(path) if path else None

    """Per-episode driver for readiness measurement + loop-stop signal.

    Owns nothing mutable on the pipeline side — only inspects the buffer and
    returns a verdict the loop interprets. Designed so the loop call site is
    a small, easily-deletable wedge.
    """

    cfg: Phase1ReadinessHookConfig
    _last_report: Optional[Phase1ReadinessReport] = field(default=None, init=False)
    _stopped_at: Optional[int] = field(default=None, init=False)
    _stop_reason: Optional[str] = field(default=None, init=False)

    @property
    def enabled(self) -> bool:
        return self.cfg.enabled

    @property
    def last_report(self) -> Optional[Phase1ReadinessReport]:
        return self._last_report

    @property
    def stopped_at(self) -> Optional[int]:
        return self._stopped_at

    @property
    def stop_reason(self) -> Optional[str]:
        return self._stop_reason

    def should_stop(self, episodes_done: int, buffer,
                    episode_label: Optional[int] = None) -> bool:
        """Called after each round-end (round_robin) or each episode (seed_major).

        Args:
            episodes_done: cumulative episodes completed so far (1-indexed).
                THIS is what ``phase1_min`` / ``phase1_max`` are compared to —
                NOT the folder name (which in round_robin is ``batch × K + slot
                + 1`` and bears no relation to "episodes done").
            buffer: ``SubgoalBuffer`` instance from the subgoal selector.
            episode_label: optional folder NN for trace logging (e.g., 91
                when episodes_done=10 in round_robin). Display-only.

        Per-seed minimum coverage in round_robin is enforced *implicitly* by
        ``phase1_min`` — hook called only at round-end means the first check
        with ``episodes_done >= phase1_min`` has each seed at
        ``ceil(phase1_min / num_seeds)`` episodes.

        Side effects: prints a bold-blue ``[method3:phase1]`` panel for each
        check (always, when enabled); records ``_last_report`` and (on stop)
        ``_stopped_at`` / ``_stop_reason``.
        """
        # backward-compat: callers passing episode_num as positional → both
        # treated as the cumulative count (correct in seed_major; safe sentinel
        # in round_robin if caller forgets to use the new arg).
        episode_num = episodes_done if episode_label is None else episode_label
        # ANSI colors — bold blue/cyan for high visibility against the
        # mostly-cyan/yellow episode logs.
        BLUE = "\033[1;94m"        # bold bright blue
        CYAN = "\033[1;96m"        # bold bright cyan (status line)
        GREEN = "\033[1;92m"       # ready=True highlight
        YELLOW = "\033[1;93m"      # warning/guard
        DIM = "\033[2;37m"         # dim sub-info
        RESET = "\033[0m"

        def _panel(lines: list[str], color: str = BLUE) -> None:
            bar = color + "═" * 72 + RESET
            print(bar)
            for ln in lines:
                print(color + "║ " + RESET + ln)
            print(bar)

        if not self.cfg.enabled:
            return False
        if buffer is None:
            return False

        # SubgoalBuffer 누적 검사 — 정상이면 episode 마다 append 됨.
        # empty 또는 stagnant 면 노랑 warning (= readiness 측정 의미 없음).
        buf_total = int(buffer.total_size()) if buffer else 0
        prev_total = int(getattr(self, "_prev_buf_total", 0))
        delta = buf_total - prev_total
        if buf_total == 0 and episodes_done >= 2:
            print(f"{YELLOW}[method3:phase1] WARN: SubgoalBuffer EMPTY after "
                  f"{episodes_done} episodes — readiness 측정 불가{RESET}")
            print(f"{YELLOW}    → 확인: 1) subgoal_selector hook 활성화 여부  "
                  f"2) TRUE-accept 후 buffer.append 호출 chain  "
                  f"3) phase1_config.yaml.readiness.enabled=true{RESET}")
        elif delta == 0 and episodes_done >= 2:
            print(f"{YELLOW}[method3:phase1] WARN: buffer 증가 없음 "
                  f"(episode {episodes_done}, total stays at {buf_total}){RESET}")
            print(f"{YELLOW}    → 직전 episode 가 TRUE-accept 됐는지 확인. "
                  f"FALSE 면 entry append 자연 보존 (intentional skip 일 수도){RESET}")
        elif buf_total > 0 and prev_total == 0:
            print(f"{YELLOW}[method3:phase1] ✓ SubgoalBuffer 첫 entry 누적: "
                  f"total={buf_total}, skills={buffer.skill_ids()}{RESET}")
        self._prev_buf_total = buf_total

        # max guard fires regardless of readiness — compared to CUMULATIVE.
        if episodes_done >= self.cfg.phase1_max:
            _panel(
                [
                    f"{YELLOW}[method3:phase1] MAX GUARD{RESET} "
                    f"done={episodes_done} ≥ B₁_max={self.cfg.phase1_max} "
                    f"(folder ep={episode_num})",
                    f"{DIM}reason: phase1_max_guard — stopping (Phase2 not yet wired){RESET}",
                ],
                color=YELLOW,
            )
            self._stopped_at = episodes_done
            self._stop_reason = "phase1_max_guard"
            return True

        # readiness check only after cumulative B₁_min.
        # silent skip 이었지만 사용자가 진행률 확인할 수 있게 한 줄 progress 로그 추가.
        # DIM 으로 noise 최소화 — 측정 panel 과 시각적 구분.
        if episodes_done < self.cfg.phase1_min:
            print(
                f"{DIM}[method3:phase1] gate skipped — "
                f"episodes_done={episodes_done}/{self.cfg.phase1_min} — "
                f"measure deferred until threshold "
                f"(folder ep={episode_num}, buffer total={buf_total}){RESET}"
            )
            return False

        report = measure_phase1_readiness_loo(buffer, self.cfg.to_readiness_config())
        self._last_report = report
        per = {k: round(v, 3) for k, v in report.per_skill.items()}
        ready_ok = report.is_ready

        # ── G_bar_phase2 — surrogate (budget_aware_phase1_boundary_rule.md §3)
        gate_g = self.cfg.phase2_potential_gain_threshold > 0.0
        g_bar, g_meta, gain_ok = 0.0, {}, True
        if gate_g:
            from method3_integration.phase2_gain_estimator import (
                GainEstimatorConfig, estimate_phase2_gain,
            )
            g_cfg = GainEstimatorConfig(
                n_probes_per_skill=self.cfg.n_probes_per_skill,
                beta=self.cfg.gain_beta, lambda_=self.cfg.gain_lambda,
                radius_k=self.cfg.radius_k,
                radius_quantile=self.cfg.radius_quantile,
                rng_seed=episode_num,
            )
            g_bar, g_meta = estimate_phase2_gain(buffer, g_cfg)
            gain_ok = g_bar >= self.cfg.phase2_potential_gain_threshold

        def _bar(value: float, tau: float, width: int = 30) -> str:
            ratio = max(0.0, min(1.0, value))
            filled = int(round(ratio * width))
            tmark = int(round(max(0.0, min(1.0, tau)) * width))
            return "".join(
                "┃" if i == tmark else "█" if i < filled else "░"
                for i in range(width)
            )

        ready_tag = (f"{GREEN}READY{RESET}" if ready_ok
                     else f"{DIM}not ready{RESET}")
        # threshold values pulled out to short locals so log lines fit one row
        thr_r = self.cfg.state_ready_threshold
        thr_g = self.cfg.phase2_potential_gain_threshold
        lines = [
            f"{BLUE}[method3:phase1] PHASE1 BOUNDARY CHECK{RESET}   "
            f"done={episodes_done}  (folder ep={episode_num})",
            f"state_readiness = {CYAN}{report.r_ready:.3f}{RESET}   "
            f"threshold={thr_r}   {ready_tag}",
            f"{CYAN}{_bar(report.r_ready, thr_r)}{RESET}  (┃ threshold)",
        ]
        if gate_g:
            gain_tag = (f"{GREEN}gain ok{RESET}" if gain_ok
                        else f"{DIM}gain low{RESET}")
            lines += [
                f"phase2_gain     = {CYAN}{g_bar:.3f}{RESET}   "
                f"threshold={thr_g}   {gain_tag}   "
                f"{DIM}[surrogate: {g_meta.get('n_probes', 0)} probes "
                f"{g_meta.get('per_skill', {})}]{RESET}",
                f"{CYAN}{_bar(g_bar, thr_g)}{RESET}  (┃ threshold)",
            ]
        lines.append(f"per-skill : {per}")
        _panel(lines, color=BLUE)

        # readiness trajectory jsonl — 분석용. 사용자 요청.
        trace_path = getattr(self, "_readiness_trace_path", None)
        if trace_path is not None:
            try:
                import json as _json, time as _time
                from pathlib import Path as _Path
                _Path(trace_path).parent.mkdir(parents=True, exist_ok=True)
                rec = {
                    "ts": _time.time(),
                    "episodes_done": int(episodes_done),
                    "episode_num": int(episode_num),
                    "state_ready": float(report.r_ready),
                    "state_ready_threshold": float(thr_r),
                    "state_ready_ok": bool(ready_ok),
                    "phase2_gain": float(g_bar) if gate_g else None,
                    "phase2_gain_threshold": float(thr_g) if gate_g else None,
                    "phase2_gain_ok": bool(gain_ok) if gate_g else None,
                    "per_skill": {k: float(v) for k, v in report.per_skill.items()},
                    "buffer_total": int(buffer.total_size()) if buffer else 0,
                    "buffer_skills": list(buffer.skill_ids()) if buffer else [],
                }
                with open(trace_path, "a", encoding="utf-8") as f:
                    f.write(_json.dumps(rec) + "\n")
            except Exception as e:
                print(f"[method3:phase1][trace] readiness save failed: {e}")

        all_pass = ready_ok and gain_ok
        if all_pass and self.cfg.auto_stop_on_ready:
            reason_detail = (
                "state_readiness ≥ threshold ∧ phase2_gain ≥ threshold" if gate_g
                else "state_readiness ≥ threshold"
            )
            _panel(
                [
                    f"{GREEN}[method3:phase1] PHASE1 COMPLETE — {reason_detail}{RESET}",
                    f"done={episodes_done}  (folder ep={episode_num})   stopping early.",
                    f"{DIM}(Phase2 transition: run --phase phase2 with remaining budget "
                    f"after VLA training.){RESET}",
                ],
                color=GREEN,
            )
            self._stopped_at = episodes_done
            self._stop_reason = "phase1_ready_and_gain" if gate_g else "phase1_ready"
            return True
        return False
