"""Per-episode Phase1 readiness check + auto-stop hook (Stage 1 wire-in).

Drives the live ``run_multiple_episodes`` / ``resume_multiple_episodes`` loop
with Phase1 termination semantics from method3 §15:

  Phase1 transition / stop:
      (t ≥ B₁_min ∧ R_ready > τ_ready)  ∨  (t ≥ B₁_max)

Since hardware Phase2 (encoder training + candidate generation + execution) is
not yet wired, "transition" here means **early stop with `transition` reason**
— the run terminates and the user can move on. When Stage 2/3 land, this hook
can be replaced by full `Method3Acquisition` driving the loop.

Readiness measurement (R_ready)
-------------------------------
The spec wants probes generated by the Phase2 candidate generator, which we
don't have yet. As a hardware-free proxy this hook uses **leave-one-out
self-coverage** over the live ``SubgoalBuffer``: each skill's entries treat
their ``terminal_region_key`` as a single-window probe and compare against the
remaining entries as the db. Same ``Phase1ReadinessConfig`` params (radius_k,
radius_quantile, k_min, tau_ready) as the spec method, so τ tuning intuition
carries over.

Interpretation:
  R_ready high  ⇔ buffer is self-dense in state-key space → support is broad
                  enough that any new episode will land in covered region.
  R_ready low   ⇔ buffer is sparse → keep collecting.

Opt-in via ``recording_config_ws*.yaml``::

    method3_phase1:
      enabled: true               # default false — full opt-in
      phase1_min: 20              # B₁_min
      phase1_max: 50              # B₁_max  (cap regardless of readiness)
      tau_ready: 0.7              # R_ready threshold
      k_min: 3
      radius_k: 5
      radius_quantile: 0.7
      auto_stop_on_ready: true    # false → measure & log only, do not stop
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import numpy as np

from method3.phase_control.phase1_readiness import (
    Phase1ReadinessConfig,
    Phase1ReadinessReport,
    SkillProbe,
    evaluate_phase1_readiness,
)


@dataclass
class Phase1ReadinessHookConfig:
    """Live-pipeline-side wrapper for ``Phase1ReadinessConfig`` + loop policy."""

    enabled: bool = False
    phase1_min: int = 20
    phase1_max: int = 50
    tau_ready: float = 0.7
    k_min: int = 3
    radius_k: int = 5
    radius_quantile: float = 0.7
    auto_stop_on_ready: bool = True

    def to_readiness_config(self) -> Phase1ReadinessConfig:
        return Phase1ReadinessConfig(
            tau_ready=self.tau_ready,
            k_min=self.k_min,
            radius_k=self.radius_k,
            radius_quantile=self.radius_quantile,
        )

    @classmethod
    def from_yaml_section(cls, section: Optional[dict]) -> "Phase1ReadinessHookConfig":
        """Build from the ``method3_phase1`` block of the recording config yaml.

        Missing block → disabled hook (defaults). Unknown keys are ignored to
        keep yaml forward-compatible with future Stage 2/3 keys.
        """
        if not section:
            return cls()
        d = dict(section)
        return cls(
            enabled=bool(d.get("enabled", False)),
            phase1_min=int(d.get("phase1_min", 20)),
            phase1_max=int(d.get("phase1_max", 50)),
            tau_ready=float(d.get("tau_ready", 0.7)),
            k_min=int(d.get("k_min", 3)),
            radius_k=int(d.get("radius_k", 5)),
            radius_quantile=float(d.get("radius_quantile", 0.7)),
            auto_stop_on_ready=bool(d.get("auto_stop_on_ready", True)),
        )


def measure_phase1_readiness_loo(
    buffer, config: Phase1ReadinessConfig,
) -> Phase1ReadinessReport:
    """Leave-one-out self-coverage proxy for Phase1 readiness from live buffer.

    Each ``SubgoalBufferEntry.terminal_region_key`` becomes a 1-window probe.
    The db for that skill is the full set of keys (LOO is approximated — the
    entry's own key matches itself with distance 0 and is necessarily one
    neighbor; with ``k_min=3`` we need ≥2 *other* neighbors within ρ_m, so
    self-match doesn't trivially saturate the metric).

    Returns ``Phase1ReadinessReport`` matching the spec calculator's interface
    so logging/threshold logic stays identical.
    """
    probes: list[SkillProbe] = []
    for skill_id in buffer.skill_ids():
        entries = buffer.entries(skill_id)
        if len(entries) < 2:
            # Cold start — evaluate_phase1_readiness already returns 0.0 for
            # under-populated skills; pass a placeholder so the skill appears
            # in the report dict.
            probes.append(SkillProbe(
                skill_id=str(skill_id),
                probe_candidate_keys=[],
                db_state_keys=np.empty((0, 1), dtype=np.float64),
            ))
            continue
        keys = np.stack([
            np.asarray(e.terminal_region_key, dtype=np.float64) for e in entries
        ])
        probe_candidates = [k.reshape(1, -1) for k in keys]   # each entry = 1-window probe
        probes.append(SkillProbe(
            skill_id=str(skill_id),
            probe_candidate_keys=probe_candidates,
            db_state_keys=keys,
        ))
    return evaluate_phase1_readiness(probes, config)


@dataclass
class Phase1ReadinessHook:
    """Per-episode driver for readiness measurement + loop-stop signal.

    Owns nothing mutable on the pipeline side — only inspects the buffer and
    returns a verdict the loop interprets. Designed so the loop call site is
    a small, easily-deletable wedge.
    """

    cfg: Phase1ReadinessHookConfig
    _last_report: Optional[Phase1ReadinessReport] = field(default=None, init=False)
    _stopped_at: Optional[int] = field(default=None, init=False)
    _stop_reason: Optional[str] = field(default=None, init=False)

    @property
    def enabled(self) -> bool:
        return self.cfg.enabled

    @property
    def last_report(self) -> Optional[Phase1ReadinessReport]:
        return self._last_report

    @property
    def stopped_at(self) -> Optional[int]:
        return self._stopped_at

    @property
    def stop_reason(self) -> Optional[str]:
        return self._stop_reason

    def should_stop(self, episode_num: int, buffer) -> bool:
        """Called after each successful episode. Returns True if loop should break.

        Args:
            episode_num: 1-indexed episode counter (post-completion).
            buffer: ``SubgoalBuffer`` instance from the subgoal selector.

        Side effects: prints a bold-blue ``[method3:phase1]`` panel for each
        check (always, when enabled); records ``_last_report`` and (on stop)
        ``_stopped_at`` / ``_stop_reason``.
        """
        # ANSI colors — bold blue/cyan for high visibility against the
        # mostly-cyan/yellow episode logs.
        BLUE = "\033[1;94m"        # bold bright blue
        CYAN = "\033[1;96m"        # bold bright cyan (status line)
        GREEN = "\033[1;92m"       # ready=True highlight
        YELLOW = "\033[1;93m"      # warning/guard
        DIM = "\033[2;37m"         # dim sub-info
        RESET = "\033[0m"

        def _panel(lines: list[str], color: str = BLUE) -> None:
            bar = color + "═" * 72 + RESET
            print(bar)
            for ln in lines:
                print(color + "║ " + RESET + ln)
            print(bar)

        if not self.cfg.enabled:
            return False
        if buffer is None:
            return False

        # max guard fires regardless of readiness.
        if episode_num >= self.cfg.phase1_max:
            _panel(
                [
                    f"{YELLOW}[method3:phase1] MAX GUARD{RESET} ep={episode_num} "
                    f"≥ B₁_max={self.cfg.phase1_max}",
                    f"{DIM}reason: phase1_max_guard — stopping (Phase2 not yet wired){RESET}",
                ],
                color=YELLOW,
            )
            self._stopped_at = episode_num
            self._stop_reason = "phase1_max_guard"
            return True

        # readiness check only after B₁_min.
        if episode_num < self.cfg.phase1_min:
            return False

        report = measure_phase1_readiness_loo(buffer, self.cfg.to_readiness_config())
        self._last_report = report
        per = {k: round(v, 3) for k, v in report.per_skill.items()}

        # build a clear status bar visualizing R_ready vs τ
        ratio = max(0.0, min(1.0, report.r_ready))
        filled = int(round(ratio * 30))
        tau_mark = int(round(self.cfg.tau_ready * 30))
        bar_chars = []
        for i in range(30):
            if i == tau_mark:
                bar_chars.append("┃")          # tau marker
            elif i < filled:
                bar_chars.append("█")
            else:
                bar_chars.append("░")
        bar = "".join(bar_chars)

        ready_str = (f"{GREEN}READY{RESET}" if report.is_ready
                     else f"{DIM}not ready{RESET}")
        _panel(
            [
                f"{BLUE}[method3:phase1] PHASE1 READINESS CHECK{RESET}   ep={episode_num}",
                f"R_ready = {CYAN}{report.r_ready:.3f}{RESET}   τ={self.cfg.tau_ready}   "
                f"{ready_str}",
                f"{CYAN}{bar}{RESET}  (┃ = τ marker)",
                f"per-skill : {per}",
            ],
            color=BLUE,
        )

        if report.is_ready and self.cfg.auto_stop_on_ready:
            _panel(
                [
                    f"{GREEN}[method3:phase1] PHASE1 COMPLETE — R_ready > τ{RESET}",
                    f"ep={episode_num}   stopping early.",
                    f"{DIM}(Stage 1: Phase2 transition not wired — would build encoder + "
                    f"Phase2MISelector here.){RESET}",
                ],
                color=GREEN,
            )
            self._stopped_at = episode_num
            self._stop_reason = "phase1_ready"
            return True
        return False
