# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import preselective_pb2 as preselective__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in preselective_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PreselectiveAcquirerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlanAndSelect = channel.unary_unary(
                '/preselective.PreselectiveAcquirer/PlanAndSelect',
                request_serializer=preselective__pb2.PlanRequest.SerializeToString,
                response_deserializer=preselective__pb2.PlanResponse.FromString,
                _registered_method=True)
        self.CommitToBuffer = channel.unary_unary(
                '/preselective.PreselectiveAcquirer/CommitToBuffer',
                request_serializer=preselective__pb2.CommitRequest.SerializeToString,
                response_deserializer=preselective__pb2.CommitResponse.FromString,
                _registered_method=True)
        self.Ready = channel.unary_unary(
                '/preselective.PreselectiveAcquirer/Ready',
                request_serializer=preselective__pb2.Empty.SerializeToString,
                response_deserializer=preselective__pb2.ServerInfo.FromString,
                _registered_method=True)


class PreselectiveAcquirerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlanAndSelect(self, request, context):
        """Plan K candidates via curobo + run IG·AC + return chosen trajectory.
        Server stores (ctx, selection) by selection_id for deferred commit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitToBuffer(self, request, context):
        """After task judge returns TRUE, commit pending selections to buffer.
        Pass an empty selection_ids list with judge_true=false to discard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ready(self, request, context):
        """Health check + server config snapshot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PreselectiveAcquirerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlanAndSelect': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanAndSelect,
                    request_deserializer=preselective__pb2.PlanRequest.FromString,
                    response_serializer=preselective__pb2.PlanResponse.SerializeToString,
            ),
            'CommitToBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitToBuffer,
                    request_deserializer=preselective__pb2.CommitRequest.FromString,
                    response_serializer=preselective__pb2.CommitResponse.SerializeToString,
            ),
            'Ready': grpc.unary_unary_rpc_method_handler(
                    servicer.Ready,
                    request_deserializer=preselective__pb2.Empty.FromString,
                    response_serializer=preselective__pb2.ServerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'preselective.PreselectiveAcquirer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('preselective.PreselectiveAcquirer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PreselectiveAcquirer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlanAndSelect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preselective.PreselectiveAcquirer/PlanAndSelect',
            preselective__pb2.PlanRequest.SerializeToString,
            preselective__pb2.PlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitToBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preselective.PreselectiveAcquirer/CommitToBuffer',
            preselective__pb2.CommitRequest.SerializeToString,
            preselective__pb2.CommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ready(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/preselective.PreselectiveAcquirer/Ready',
            preselective__pb2.Empty.SerializeToString,
            preselective__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
