# Detection Configuration
# 객체 검출 관련 설정

## 검출할 객체 목록
objects:
## ======== pnp task objects ========
  - "red block"
  - "blue dish"

## ======== fold towel task objects ========
  # - "green towel"

## ======== pick the toy and place it on the blue dish ========
  # - "the toy"
  # - "blue dish"

# 검출 타임아웃 (초)
detection_timeout: 1.5

# 검출 결과 시각화 여부
visualize_detection: true
